version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: x64
environment:
  matrix:
  - cmake_build: 1
  - cmake_build: 1
    features: USE_CPU_ONLY
    run_tests: 1
  - cmake_build: 1
    features: USE_CPU_ONLY USE_BLAS
    run_tests: 1
  - msbuild: 1
skip_commits:
  files:
    - '**/*.md'
    - '**/.gitignore'
    - scripts/
    - training/
    - AUTHORS
    - COPYING
install:
- cmd: nuget restore msvc\VS2017 -PackagesDirectory msvc\packages
cache: msvc\packages -> appveyor.yml
build_script:
- cmd: if "%cmake_build%"=="1" msvc\VS2017\cmake_build.bat
- cmd: if "%msbuild%"=="1" msbuild /t:build msvc\VS2017\leela-zero.vcxproj

test_script:
- cmd: if "%run_tests%"=="1" cd build && Release\tests.exe
